name: user_repository
description: The Repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equatable: ^2.0.5
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  # firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  # path: ^1.8.3
  shared_preferences: ^2.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true